# Generated by Django 3.0.4 on 2020-04-03 17:42

from django.db import migrations
import lessons.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', lessons.models.UserManager()),
            ],
        ),
    ]
