# Generated by Django 3.0.4 on 2020-04-07 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20200407_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodule',
            name='lesson_link',
        ),
        migrations.RemoveField(
            model_name='coursemodule',
            name='presentation_link',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('presentation_link', models.URLField(null=True)),
                ('lesson_link', models.URLField(null=True)),
                ('next_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_lesson', to='lessons.Lesson')),
            ],
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='first_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_module', to='lessons.Lesson'),
        ),
    ]
