# Generated by Django 3.0.4 on 2020-04-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20200407_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
